FROM golang:1.26.2

WORKDIR /app

RUN apt-get update && apt-get install -y git

# Cache de deps Go
COPY go.mod go.sum ./
RUN go mod download

# Instal·lar air
RUN go install github.com/air-verse/air@latest

CMD ["air", "-c", ".air.toml"]